// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wahqfdgybivndsplphro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhaHFmZGd5Yml2bmRzcGxwaHJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0Mjk2MzAsImV4cCI6MjA3MzAwNTYzMH0.7opVVmOrrrSItTQo12HLbXolIeGe6nsTA3n2RgRug0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});