name: Nightly ETL Pipeline

on:
  schedule:
    # Run every night at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  etl:
    runs-on: ubuntu-latest
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      EDGAR_USER_AGENT: ${{ secrets.EDGAR_USER_AGENT }}
      OPENFDA_API_KEY: ${{ secrets.OPENFDA_API_KEY }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r etl/requirements.txt
        
    - name: Run ClinicalTrials.gov ETL
      run: |
        cd etl
        python ctgov_ingest.py
      continue-on-error: true
      
    - name: Run FDA Ap
